GET http://localhost:3001/api/notes

### Another Request
GET http://localhost:3001/api/notes/2

###
GET http://localhost:3001/api/notes/100

###
GET http://localhost:3001/api/notes/69817f51fade5e4bbf2f7ef9